<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>HNSB | Terms and Condition</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="" name="description" />
    <meta content="HNSB" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="{{ asset('/assets/images/favicon.jpg') }}">

    <!-- Bootstrap css -->
    <link href="{{ asset('/assets/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
    <!-- App css -->
    <link href="{{ asset('/assets/css/app.min.css') }}" rel="stylesheet" type="text/css" id="app-style" />
    <!-- icons -->
    <link href="{{ asset('/assets/css/icons.min.css') }}" rel="stylesheet" type="text/css" />
    <!-- Head js -->
    <script src="{{ asset('/assets/js/head.js') }}"></script>
</head>

<!-- body start -->
<body>
    <!-- Begin page -->
    <div id="wrapper">
        <div class="">
            <div class="content mb-3">
                <!-- Start Content-->
                <div class="container-lg">
                    <!-- start page title -->
                    <div class="row">
                        <div class="col-12">
                            <div class="page-title-box">
                                <center>
                                    <h2 class="mt-5 mb-5">Terms and Conditions</h2>
                                </center>

                                {{-- <p style="text-align:justify" class="sub-header"> --}}
                                    {{-- Welcome to the Website of HNSB. This website is best viewed using a contemporary browser. </p> --}}
                                <p style="text-align:justify" class="sub-header">This document is an electronic record in terms of the Information Technology Act, 2000 ("IT Act") and rules thereunder, and is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines and Digital Media Ethics Code) Rules 2021, which mandates for publishing of rules and regulations, privacy policy and terms of use for access or usage of the Website. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
                                <p style="text-align:justify" class="sub-header">The Platform is owned by The Himmatnagar Nagrik Sahkari Bank Ltd Science College with its address at The HNSB LTD Science College, College Campus, Motipura, Himatnagar - 383 001. Dist Sabarkantha - Gujarat - India (hereinafter referred to as "HNSB Science College, we, us, and our")</p>

                                <p style="text-align:justify" class="sub-header">Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with The Himmatnagar Nagrik Sahkari Bank Ltd Science College and these terms and conditions including the policies constitute Your binding obligations, with HNSB Science College.</p>

                                <p style="text-align:justify" class="sub-header">For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer on the Platform by providing Registration Data while registering on the Platform as Registered User using the computer systems. HNSB Science College allows the User to surf the Platform or making purchases without registering on the Platform. The term "We", "Us", "Our" shall mean The Himmatnagar Nagrik Sahkari Bank Ltd Science College.</p>

                                <p style="text-align:justify" class="sub-header"> Use of this website is offered to you on your acceptance of these Terms of Use and other notices posted on this website. </p>

                                <p style="text-align:justify" class="sub-header"> These terms of use constitute the agreement between HNSB Science College, and you as a user who accesses or establishes a connection. If you do not agree to the provisions of this agreement or are not satisfied with this please do not use the site. </p>

                                <p style="text-align:justify" class="sub-header">This website, including all content and functions made available is designed, developed and maintained by the HNSB Science College. When you access, browse or use this website you accept, without limitation or qualification, the terms and conditions set forth below. </p>
                                <p style="text-align:justify" class="sub-header">You may search, retrieve, view, download, and print content on this site for personal use and shall make no other use of such content, without the written permission from HNSB Science College. You agree that you do not acquire any ownership rights in the content that you use. </p>

                                <p style="text-align:justify" class="sub-header">Any unauthorized use of the content and proprietary logos, service marks, and trademarks may violate copyright laws, trademark laws, the laws of privacy and publicity and certain civil and criminal statutes. </p>

                                <p style="text-align:justify" class="sub-header">HNSB Science College is the exclusive copyright owner of all programming/designing code that is used on this site. Any reproduction or redistribution of programming/designing code is expressly prohibited by law, and may result in drastic civil and criminal penalties. Violators will be prosecuted to the maximum extent permitted by law. </p>

                                <p style="text-align:justify" class="sub-header">HNSB Science College reserves the right to report any wrongdoing, if and when we become aware of it, to any applicable government agencies. To the maximum extent permitted by applicable law, you will defend, indemnify and hold harmless HNSB Science College from and against all claims, liability, and expenses arising out of your use of the Site, your breach of any provision of this Agreement and/or any intentional wrongdoing by you. HNSB Science College reserves the right, in its sole discretion and at your own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you. You will cooperate as fully as reasonably required in the defense of any claim. </p>
                                <h5>No unlawful, infringing or offensive activity</h5>
                                <p style="text-align:justify" class="sub-header">Your use of this Website is in compliance with all the applicable laws including but not limited to Information Technology Act, 2000 and the Rules made thereunder. You must not post/transmit or enable another person to post/transmit via the Website any information or material or otherwise use the Website for any activity which breaches any laws or regulations, infringes a third party’s rights or privacy or is contrary to any applicable laws. This Website or any Services under this Website are accessed via the World Wide Web, which is independent of the Website. Your use of the World Wide Web is solely at your own risk and subject to all applicable laws and regulations. We have no responsibility for any information or service obtained by you on the World Wide Web.</p>
                                <p style="text-align:justify" class="sub-header">You may not use any device, software or routine, including but not limited to any viruses, trojans, worms, time bombs, denial-of-service attacks, other malicious code or repeated "hacks" or "attacks" on the HNSB Science College server, intended to damage or interfere with the proper working of the Site or to surreptitiously intercept or expropriate any system, data or personal information from the Site. You may not take any action, which imposes an unreasonable or disproportionately large load on the Site's infrastructure, including but not limited to denial of service attacks, "spam" or any other such unsolicited overload technique. </p>
                                <h5>Intellectual Property</h5>
                                <p style="text-align:justify" class="sub-header">All intellectual property rights in this web site, design, text, graphics, applications, software, underlying source code and all other aspects belong to us and or our Affiliates.</p>
                                <p style="text-align:justify" class="sub-header">HNSB Science College in its sole discretion may change any or all of the provisions of this Agreement at any time. Any changes to this Agreement will be effective immediately upon your use of this Site. Your use of this Site after any changes to this Agreement have been made will be deemed your acceptance of the changes. You agree it is your sole responsibility to periodically check these terms of use for changes. </p>
                                
                                <h5>Limitation of Liability</h5>
                                <p style="text-align:justify" class="sub-header">In no event shall The Himmatnagar Nagrik Sahkari Bank Ltd Science College be liable for any special, incidental, indirect or consequential damages of any kind in connection with these terms of use, even if user has been informed in advance of the possibility of such damages.</p>

                                <h5>Suspension or Modifications of Terms and Conditions</h5>
                                <p style="text-align:justify" class="sub-header">You accept and agree that the HNSB Science College may suspend or vary the whole or any part of the Site for any reason, at any time at its sole discretion without prior notice. The Company hereby reserves the right to make subsequent changes to, the Site or its content and services may be modified, varied, supplemented or withdrawn.</p>
                                <h5>Governing Law and Jurisdiction</h5>
                                <p style="text-align:justify" class="sub-header">
                                These terms and conditions are governed in accordance with the laws of India. Any dispute shall be subject to the exclusive jurisdiction of courts in Himmatnagar, Gujarat, India.
                                </p>
                                <center>
                                    <h2 class="mt-5 mb-5">Refund & Cancellation Policy</h2>
                                </center>

                                <ul class="mb-5">
                                    <li>
                                        <p style="text-align:justify" class="sub-header">Once admission fee (Rs. 100/-) is paid will not be refunded in any circumstances</p>
                                    </li>
                                    <li>
                                        <p style="text-align:justify" class="sub-header">College semester fees paid will subject to be refunded based on the college's decision</p>
                                    </li>
                                </ul>
                                

                            </div>
                        </div>
                    </div>
                    <!-- end page title -->

                </div> <!-- container -->

            </div> <!-- content -->

            <footer class="footer footer-alt" style="background-color:#98a6ad1f">
                <div class="row">
                    <div class="col-md-5">
                        <div class="text-md-start footer-links d-none d-sm-block">
                            <a class="text-dark" href="https://www.hnsbscihmt.org" target="_blank">www.hnsbscihmt.org</a>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <script>
                            document.write(new Date().getFullYear())
                        </script> &copy; Developed by <a href="#" class="text-dark">Bitsapp</a>
                    </div>
                    <div class="col-md-5">
                        <div class="text-md-end footer-links d-none d-sm-block">
                            <a class="text-dark" href="{{ route('login')}}">Login</a>
                            <a class="text-dark" href="{{ route('register')}}">Registration</a>
                            <a class="text-dark" href="{{ route('aboutUs')}}">About Us</a>
                            <a class="text-dark" href="{{ route('termsAndConditions')}}">Terms & Conditions</a>
                            <a class="text-dark" href="{{ route('privacyPolicy')}}">Privacy Policy</a>
                            <a class="text-dark" href="{{ route('contactUs')}}">Contact Us</a>
                        </div>
                    </div>
                </div>
            </footer>

        </div>

        <!-- ============================================================== -->
        <!-- End Page content -->
        <!-- ============================================================== -->


    </div>
    <!-- END wrapper -->

    <!-- Right bar overlay-->
    <div class="rightbar-overlay"></div>

    <!-- Vendor js -->
    <script src="{{ asset('/assets/js/vendor.min.js') }}"></script>

    <!-- App js -->
    <script src="{{ asset('/assets/js/app.min.js') }}"></script>

</body>
</html>
